#!/usr/bin/env bash

#bin-update - A script that updates bin folder

echo
echo "================================================================"
echo "============== UPDATING BIN EXECUTABLES & CONFIGS =============="
echo "================================================================"
echo

cd ~/bin

BIN_LOCATION="$(pwd)"

if hash gpg2 2>/dev/null; then
    GPG_EXECUTABLE_PATH=`which gpg2`
else
    GPG_EXECUTABLE_PATH=`which gpg`
fi

GPG_EXECUTABLE_NAME=`basename $GPG_EXECUTABLE_PATH`
echo "NAME: $GPG_EXECUTABLE_NAME"

echo "Found GPG executable: $GPG_EXECUTABLE_NAME"

if [[ -z $GPG_EXECUTABLE_NAME ]]
then
    echo "GPG executable not found. Exiting..."
    exit 1
fi

echo "Updating repo..."
git pull --rebase

echo "Adding exectubale privilige to scripts..."
chmod +x ~/bin/exec/*

cp ~/bin/.zshrc ~/ && echo "Copied .zshrc to ~/"
cp ~/bin/.zshenv ~/ && echo "Copied .zshenv to ~/"
cp ~/bin/.zshfn ~/ && echo "Copied .zshfn to ~/"
cp ~/bin/.npmrc ~/ && echo "Copied .npmrc to ~/"
cp ~/bin/sheldon.toml ~/.config/sheldon/plugins.toml && echo "Copied sheldon.toml to ~/.config/sheldon/plugins.toml"
cp ~/bin/.gitconfig ~/ && echo "Copied .gitconfig to ~/"

OS_NAME=$(uname -s)

if [[ $OS_NAME = "Darwin" ]]
then
    sed -i "" "s/{{GPG_EXECUTABLE}}/"$GPG_EXECUTABLE_NAME"/g" ~/.gitconfig && echo "GPG executable updated"
else
    sed -i "s/{{GPG_EXECUTABLE}}/"$GPG_EXECUTABLE_NAME"/g" ~/.gitconfig && echo "GPG executable updated: $GPG_EXECUTABLE_NAME"
fi
