#!/usr/bin/env bash

#bin-update - A script that updates bin folder

echo "==============UPADTING BIN EXECUTABLES & CONFIGS=============="

cd ~/bin

BIN_LOCATION="$(pwd)"
EXTERNAL_EXECS_PATH="$BIN_LOCATION/exec/external"
NGROK_EXEC_PATH="$EXTERNAL_EXECS_PATH/ngrok"

if hash gpg2 2>/dev/null; then
    GPG_EXECUTABLE_PATH=`which gpg2`
else
    GPG_EXECUTABLE_PATH=`which gpg`
fi

GPG_EXECUTABLE_NAME=`basename $GPG_EXECUTABLE_PATH`

echo "Found GPG executable: $GPG_EXECUTABLE_NAME"

if [[ -z $GPG_EXECUTABLE_NAME ]]
then
    echo "GPG executable not found. Exiting..."
    exit 1
fi

echo "Updating repo..."
git pull --rebase

echo "Adding exectubale privilige to scripts..."
chmod +x ~/bin/exec/* 

cp ~/bin/.zshrc ~/ && echo "Copied .zshrc to ~/"
cp ~/bin/.npmrc ~/ && echo "Copied .npmrc to ~/"
cp ~/bin/.gitconfig ~/ && echo "Copied .gitconfig to ~/"

OS_NAME=$(uname -s)

if [[ $OS_NAME = "Darwin" ]]
then
    sed -i "" "s/{{GPG_EXECUTABLE}}/"$GPG_EXECUTABLE_NAME"/g" ~/.gitconfig && echo "GPG executable updated"
else
    sed -i "s/{{GPG_EXECUTABLE}}/"$GPG_EXECUTABLE_NAME"/g" ~/.gitconfig && echo "GPG executable updated"
fi

if [[ ! -f $NGROK_EXEC_PATH ]]
then
	OS_NAME_LOWERCASE=$(echo $OS_NAME | tr '[:upper:]' '[:lower:]')
	echo "ngrok not found."
	echo "Downloading file..."

	echo $EXTERNAL_EXECS_PATH

	curl "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-$OS_NAME_LOWERCASE-amd64.zip" \
	--create-dirs \
	-o "$EXTERNAL_EXECS_PATH/ngrok.zip" && \
	unzip "$EXTERNAL_EXECS_PATH/ngrok.zip" -d "$EXTERNAL_EXECS_PATH" && \
	find "$EXTERNAL_EXECS_PATH" -name "*.zip" | xargs rm
fi
