#!/usr/bin/env bash

#jenkins-cli - A wrapper script for jenkins cli

COMMAND=${1:-help}
SHELL_CONFIG_FILE_NAME=".zshrc"
JENKINS_JAR_PATH="./external/jenkins-cli.jar"

commonConfirm() {
    MESSAGE=${1:-Is this correct?}
    DEFAULT_RESPONSE=${2:-[Y/n]}

    read -p "$MESSAGE $DEFAULT_RESPONSE: " -n 1 -r
    echo

    if [[ $DEFAULT_RESPONSE = "[Y/n]" ]]
    then
        CONDITION_VALUE=yY
    else
        CONDITION_VALUE=nN
    fi
}

invertedConfirm() {
    commonConfirm "$1" "$2"

    if [[ $REPLY =~ ^[$CONDITION_VALUE]$ ]] || [[ $REPLY == "" ]]
    then
        return 1
    else
        return 0
    fi
}

confirm() {
    commonConfirm "$1" "$2"

    if [[ $REPLY =~ ^[$CONDITION_VALUE]$ ]] || [[ $REPLY == "" ]]
    then
        return 0
    else
        return 1
    fi
}

addJenkinsEnvVariablesToProfile() {
    if [[ ! -f ~/$SHELL_CONFIG_FILE_NAME ]]
    then
        echo "File not found. Creating new file..."
        touch ~/$SHELL_CONFIG_FILE_NAME
    else
        sed -i '/# JENKINS INFO/d' ~/$SHELL_CONFIG_FILE_NAME
        sed -i '/export ENV_JENKINS_URL/d' ~/$SHELL_CONFIG_FILE_NAME
        sed -i '/export ENV_JENKINS_JAR_PATH/d' ~/$SHELL_CONFIG_FILE_NAME
    fi

    echo "# JENKINS INFO" >> ~/$SHELL_CONFIG_FILE_NAME
    echo "export ENV_JENKINS_URL=\"$JENKINS_URL\"" >> ~/$SHELL_CONFIG_FILE_NAME
    echo "export ENV_JENKINS_JAR_PATH=\"$JENKINS_JAR_PATH\"" >> ~/$SHELL_CONFIG_FILE_NAME

    . ~/$SHELL_CONFIG_FILE_NAME
}

enterJenkinsInfo() {
    read -p "Enter Jenkins URL: " JENKINS_URL

    echo "Jenkins URL:" $JENKINS_URL

    invertedConfirm && echo "Resetting Jenkins info..." && enterJenkinsInfo

    confirm "Do you want to store these variables?" && addJenkinsEnvVariablesToProfile
}

if [[ -z $ENV_JENKINS_URL ]]
then
        echo "Environment variables for Jenkins not detected!"
        echo "Entering environment variable setup..."

        enterJenkinsInfo
else
	JENKINS_URL=$ENV_JENKINS_URL
fi

if [[ ! -f $JENKINS_JAR_PATH ]]
then
	echo "jenkins-cli.jar not found."
	echo "Downloading file..."

	curl -v --create-dirs --url $JENKINS_URL/jnlpJars/jenkins-cli.jar --output $JENKINS_JAR_PATH 
fi

read -p "Enter Jenkins username: " JENKINS_USERNAME
read -s -p "Enter Jenkins password: " JENKINS_PASSWORD
echo ""

java -jar $JENKINS_JAR_PATH -s $JENKINS_URL $1 --username $JENKINS_USERNAME --password $JENKINS_PASSWORD
